# Generated by Django 4.2.4 on 2023-09-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("audio", models.FileField(upload_to="audio_files/")),
                ("uploaded_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
