# Generated by Django 4.2.4 on 2024-07-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mind_charger", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="audiofile",
            name="title",
        ),
        migrations.AddField(
            model_name="audiofile",
            name="button_id",
            field=models.CharField(
                choices=[
                    ("01", "01"),
                    ("02", "02"),
                    ("03", "03"),
                    ("04", "04"),
                    ("05", "05"),
                    ("06", "06"),
                    ("07", "07"),
                    ("08", "08"),
                    ("09", "09"),
                    ("10", "10"),
                ],
                default="01",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="date",
            field=models.DateField(default="2024-06-10"),
            preserve_default=False,
        ),
    ]
