# Generated by Django 4.2.4 on 2023-09-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SSIDData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ssid", models.CharField(max_length=255)),
                ("pwd", models.CharField(max_length=255)),
                ("mac", models.CharField(max_length=255)),
            ],
        ),
    ]
