# Generated by Django 4.2.4 on 2024-01-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basicuser", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ssiddata",
            name="ssid",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
